version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "8000:8000"  # Mapeia a porta 8000 do contêiner para a porta 8000 do host (API HTTP)
      - "50051:50051" # Mapeia a porta 50051 do contêiner para a porta 50051 do host (API gRPC)
      - "8080:8080" # Mapeia a porta 8080 do contêiner para a porta 8080 do host (GraphQL)
    depends_on:
      - mysql
      - rabbitmq
    volumes:
      - ./cmd/ordersystem/.env:/app/.env

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  migrate:
    image: migrate/migrate
    container_name: migrate
    command: [
      "-path", "/migrations",
      "-database", "mysql://root:root@tcp(mysql:3306)/orders",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - mysql
volumes:
    db_data: {}
